trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webAppName: 'r3d-r3dc7z'

stages:

- stage: Build_Test
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      displayName: 'Build'
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          \**\AdventureWorks.Tests.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'buildArtifact'

#- stage: Deploy
#  displayName: Deploy
#  jobs:
#  - job: Deploy
#    displayName: Deploy
#    steps:
#    - task: DownloadBuildArtifacts@0
#      inputs:
#        buildType: 'current'
#        downloadType: 'single'
#        artifactName: 'buildArtifact'
#        downloadPath: '$(Build.ArtifactStagingDirectory)'
#    - task: AzureRmWebAppDeployment@4
#      inputs:
#        ConnectionType: 'AzureRM'
#        azureSubscription: 'Visual Studio Professional(dda2a232-c1b2-433a-a1e5-1d8086dd0e30)'
#        appType: 'webApp'
#        WebAppName: $(webAppName)
#        Package: '$(Build.ArtifactStagingDirectory)\**\WebApp.zip'